spring.application.name=app_saos
spring.datasource.url=jdbc:postgresql://localhost:5432/SAOS
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update

spring.jwt.secret=thisIsMysecregtfrdesww233eggtffeeddgkjjhhtdhttebd54ndhdhfhhhshs8877465sbbdd

weather.api.key=e7a0xxxxxxxxxxxxxxxxxxxxxxxxxxx

server.port=8443
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=https
